<?php
Language::add([
    'are_you_sure_to_delete' => 'Biztosan törölni akarod?',
    'delete' => 'Törlés',
    'properties' => 'Tulajdonságok',
    'edit' => 'Szerkeszt',
    
    'there_is_no_record_in_the_database' => 'Még nincs adat az adatbázisban.',
    "property_type_input"=>"Input type field",
    "property_type_select"=>"Select type field",
    "property_type_checkbox"=>"Checkbox type field",
    
    "product_status_active"=>'Aktív',
    "product_status_inactive"=>'Inaktív',
    "product_no_variants"=>'No variants',
    
    "product_default_image"=>'Alapértelmezett',
    "product_image"=>'Egyedi kép #db# db',
    
    
    'table_head_id'                 => '#Azonosító',
    'table_head_name'               => 'Név',
    'table_head_operations'         => 'Műveletek',
    'table_head_values'             => 'Értékek',
    'table_head_type'               => 'Típus',
    'table_head_status'             => 'Állapot',
    'table_head_compare_at_price'   => 'Lista ár',
    'table_head_price'              => 'Ár',
    'table_head_discount_price'     => 'Kedvezményes Ár',
    'table_head_discount_percent'   => 'Kedvezmény százalék',
    'table_head_quantity'           => 'Mennyiség',
    'table_head_variants'           => 'Variánsok',
    'table_head_description'        => 'Description',
    'table_head_delete'             => 'Delete',
    'table_head_total'              => 'Total',
    'table_head_domain'             => 'Domain',
    'table_head_priority'           => 'Priority',
    'table_head_delete'             => 'Delete',
    'table_head_lower_value'        => 'Lower value',
    'table_head_higher_value'       => 'Higher value',
    'table_head_date_start'         => 'Start Date',
    'table_head_date_end'           => 'End Date',
    'table_head_tax_percent'        => 'Tax percent',
    'table_head_tax_value'          => 'Tax value',
    'table_head_original_text'      => 'Eredeti szöveg',
    'table_head_translated_text'    => 'Lefordított szöveg',
    
    "product_no_variants"=>'No variants',
    "image_error_no_image_id"=>'Bad parameters - Empty image ID',
    "image_error_no_image_ref_id"=>'Bad parameters - Empty reference ID',
    "image_error_no_image_type"=>'Bad parameters - Empty image type',
    "image_error_no_action"=>'Bad parameters - Empty action',
    
    "image_error_status"=>'Unsuccess operation',
    
    
    "order_type_price_asc"=>"Ár szerint növekvő",
    "order_type_price_desc"=>"Ár szerint csökkenő",
    "order_type_name_asc"=>"Név A-Z szerint",
    "order_type_name_desc"=>"Név Z-A szerint",
    
    
    "compare_maximum_element"=>"Több elem nem adható az összehasonlításhoz",
    "compare_bad_type"=>"Csak azonos típusú termékek hasonlíthatóak össze",
    "compare_bad_parameter"=>'Hibás termék azonosító',
    "compare_empty_list"=>'Nincs mit összehasonlítani',
    "compare_one_element"=>'Nincs mit összehasonlítani, csak egy elem van a listán',
    "compare"=>'Összehasonlítás eredménye',
    
    
    'priority_secondary' => 'Másodlagos',
    'priority_primary' => 'Elsődleges',

    /* HISTORY */    
    "product_collect_category_history_new" => "Új kategória felvéve",
    "product_collect_category_history_modify" => "Kategória módosítása.",
    "product_collect_category_history_modify_before" => "Módosított kategória korábbi neve: ",
    "product_collect_category_history_modify_after" => "Módosított kategória új neve: ",
    "product_collect_category_history_delete" => "Törölt egy kategóriát",
    "product_collect_category_name" => "Category name",
    "product_collect_type_history_create" => "Új termék típust hozott létre",
    "product_collect_type_history_modify" => "Módosított egy termék típust",
    "product_collect_type_history_name_before" => "Régi név",
    "product_collect_type_history_name_after" => "Új név",
    "product_collect_variant_history_create" => "Új variánst hozott létre.",
    "product_collect_variant_history_modify" => "Módosított egy variánst",
    "product_collect_variant_history_name_before" => "Variáns neve módosítás előtt",
    "product_collect_variant_history_name_after" => "Variáns neve módosítás után",
    "product_collect_variant_value_history_create" => "Új variáns értéket vett fel",
    "product_collect_variant_value_history_modify" => "Módosított egy variáns értéket",
    "product_collect_variant_value_history_name_before" => "A variáns értéke módosítás előtt",
    "product_collect_variant_value_history_name_after" => "A variáns értéke módosítás után",
    "product_collect_type_variant_change_history_name" => "Módosította a termék típus variánst. Termék típus variáns #ID-k: ",
    "product_collect_type_variant_no_variant_history_name" => "Nincs variáns beállítva",
    "product_collect_property_history_name_new" => "New product property",
    "product_collect_property_history_name_modify" => "Modidfy product property",
    "product_collect_property_history_name_before_change" => "Módosítás előtti név",
    "product_collect_property_history_name_after_change" => "Módosítás utáni név",
    "product_collect_property_name_value_history_new" => "Hozzáadott egy új értéket a property-hez",
    "product_collect_property_name_value_history_modify" => "Módosított egy property értékén",
    "product_collect_property_name_value_history_before_change" => "Módosítás előtti érték",
    "product_collect_property_name_value_history_after_change" => "Módosítás utáni érték",
    "product_collect_type_property_change_history" => "Set product collect property type. Product property #ID-s: ",
    "product_collect_type_property_delete_history" => "Törölte a termék típus property-t: ",
    "product_collect_variant_delete_history" => "Törölt egy termék variánst.",
    "product_collect_history_create" => "Új termék gyűjtőt hozott létre",
    "product_collect_history_modify" => "Módosított egy termék gyűjtőt.",
    "product_collect_delete_history" => "Törölt egy termék gyűjtőt.",
    "product_collect_product_history_create" => "Egy új terméket tett a gyűjtőbe",
    "product_collect_product_history_modify" => "Módosított egy terméket a termék gyűjtőben",
    "product_collect_product_history_delete" => "Törölt egy terméket a termék gyűjtőből",
    "product_collect_product_regenerate_history" => "Újragenerálta a termékeket a termékgyűjtőben.",
    "product_collect_set_chekcbox_values_history" => "Módosította a checkbox tulajdonságokat a termék gyűjtőben",
    "product_collect_set_checkbox_values_setted_values_history" => "Beállított értékek",
    "product_collect_set_checkbox_values_no_values_setted_history" => "Nincs beállított érték",
    
	'product_category_sort_by_manual' => 'Manually',
	'product_category_sort_by_best_selling' => 'By best selling',
	'product_category_sort_by_title_ascending' => 'Alphabetically: A-Z',
	'product_category_sort_by_title_descending' => 'Alphabetically: Z-A',
	'product_category_sort_by_price_ascending' => 'By price: Highest to lowest',
	'product_category_sort_by_price_descending' => 'By price: Lowest to highest',
	'product_category_sort_by_created_ascending' => 'By date: Newest to oldest',
	'product_category_sort_by_created_descending' => 'By date: Oldest to newest',
    
]);
